# Generated by Django 3.1.7 on 2021-03-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20210317_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='test_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_correct_1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_correct_2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_correct_3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_correct_4',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.questions')),
            ],
        ),
    ]
