# Generated by Django 3.1.7 on 2021-03-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20210317_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
