# Generated by Django 3.1.7 on 2021-03-17 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_test_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 12, 54, 7, 574658, tzinfo=utc)),
        ),
    ]
