# Generated by Django 3.1.7 on 2021-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_usertests'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
