# Generated by Django 3.1.7 on 2021-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_question_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_amount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertests',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
