# Generated by Django 3.1.7 on 2021-03-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_auto_20210321_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertests',
            name='test_in_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.test'),
        ),
    ]
