# Generated by Django 3.1.7 on 2021-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_auto_20210321_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertests',
            name='is_competed',
            field=models.BooleanField(default=False),
        ),
    ]
