# Generated by Django 3.1.7 on 2021-03-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_usertests_is_competed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertests',
            name='test_in_process',
        ),
        migrations.AddField(
            model_name='usertests',
            name='test_in_process',
            field=models.ManyToManyField(blank=True, null=True, to='testing.Test'),
        ),
    ]
