# Generated by Django 3.1.7 on 2021-03-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_auto_20210323_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertests',
            name='test_in_process',
        ),
        migrations.AddField(
            model_name='usertests',
            name='test_in_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.test'),
        ),
    ]
