# Generated by Django 3.1.7 on 2021-03-24 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0019_remove_usertests_is_competed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTests',
            new_name='UserTest',
        ),
    ]
