# Generated by Django 3.1.7 on 2021-03-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='choice1_correct',
            new_name='choice1',
        ),
    ]
