# Generated by Django 3.1.7 on 2021-03-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20210316_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='questions_id_csv',
        ),
        migrations.AddField(
            model_name='questions',
            name='test_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.tests'),
            preserve_default=False,
        ),
    ]
