# Generated by Django 3.1.7 on 2021-03-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20210316_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ch1_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ch2_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='ch3_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='ch4_bool',
            field=models.BooleanField(default=False),
        ),
    ]
