# Generated by Django 3.1.7 on 2021-03-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_auto_20210317_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='ch1_bool',
            new_name='is_correct_1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ch2_bool',
            new_name='is_correct_2',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ch3_bool',
            new_name='is_correct_3',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='ch4_bool',
            new_name='is_correct_4',
        ),
    ]
