# Generated by Django 3.1.7 on 2021-03-17 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_auto_20210317_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pub_date',
            field=models.DateField(default=datetime.date(2021, 3, 17)),
        ),
    ]
